### ISSUE TITLE
add custom arguments support?

### ISSUE THREAD

**Issue by gotbletu** [McSinyx/comp#6]
can you add custom arguments support?
i would like to use task-spooler and other mpv flags with **comp**
FYI: **task-spooler (tsp)** can queue up videos/commands

normally i would use this command from the shell:
`tsp mpv --ontop --no-border --force-window --autofit=500x280 --geometry=-15-50 [URL]`

**Comment by McSinyx** [comment]
Thanks for the suggestion. The feature doesn't seem to be hard to be implement but I'm having an interview for undergrad admission this weekend so maybe we have to wait a while (the truth is since there are lots of local changes require reviewing I need to do to have a clean repo before try to do this).

Also I'm thinking about using the config file, if you want custom args to be available in the command line just tell me, then I'll need you suggestion for the meta argument name. Also be aware that `argparse` is quite limited - I chose it in the first place simply because it works outa box.

**Comment by gotbletu** [comment]
yea either is fine, config file or cli flags

something like a new flag to override any other flag, e.g:
`comp -g 'tsp mpv --ontop --no-border --force-window --autofit=500x280 --geometry=-15-50' 'https://www.youtube.com/playlist?list=PLYosk6VjN4iYItFGfacO9HBRdeUcOP7OA'`

**Comment by McSinyx** [comment]
Hoorray I was accepted by the university this morning!

Now back to the problem: I've just finished a protype for parsing mpv native arguments in configuration file. Now the config looks somewhat like [this](https://github.com/McSinyx/comp/tree/0500d98#configuration-files). ~~I'm thinking about parsing unknown command line arguments to mpv too.~~ Edit: `argparse` sucks: [`argparse.parse_known_args` just put all unknown arguments in a list](https://docs.python.org/3/library/argparse.html#argparse.ArgumentParser.parse_known_args), so this isn't worth hacking.

However, about `tsp`, what is the real purpose of it? I won't inject shell commands into the code because that's out of mpv's Python API (python-mpv by @jaseg) ability. If it's just for queueing/pausing, then I can add history to the playlist instead so you can play *each* track where you left off last time.

**Comment by gotbletu** [comment]
congrats on the university =)

well, currently you can only play one video then wait for it to end then select another one, manually.
this wastes time.

I was hoping this would be more like a music player or "streaming music video player" that has shuffle/repeat/queue features ...etc

**Comment by McSinyx** [comment]
Thank you, I have been kinda nervous for a few days.

Well, I implemented that quite a long time ago, under the term *mode*, which can be switched using `Alt-m` or set in the config file. The current mode is displayed in the bottom right corner of the screen.

My favorite are the `*-selected` which is kinda, uhm, weird. You can open `test/playlist.json` (by `comp -e json` or course) and see selected tracks are in purple. `Ctrl-Space` is current binding to (de)select entries.

**Comment by gotbletu** [comment]
if i set it to shuffle-all, is there a hotkey to skip to the next video also? like in music player you skip to next song or previous songs

**Comment by McSinyx** [comment]
It's `>`. I know the [README](https://github.com/McSinyx/comp#keyboard-control) is a bit long but you can do search in page for more goodies :wink:

Since the original problem seems to be solved now, I'll close this now. Feel free to reopen if the result isn't as good as you expected. You can also AMA here or open a new issue.
